# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Add-in.
# ------------------------------------------------------

HEADERS += cnotisettings.h \
            cnotisettings_global.h
SOURCES += cnotisettings.cpp
FORMS += ListUsers.ui \
    NewUser.ui
